import { PassThrough } from "node:stream";
import { describe, expect, test } from "vitest";

import {
  CredentialSetupCancelledError,
  readMaskedSecret
} from "../src/secret-prompt.js";

class TtyInput extends PassThrough {
  isTTY = true;
  isRaw = false;
  readonly rawModes: boolean[] = [];

  setRawMode(mode: boolean): this {
    this.rawModes.push(mode);
    this.isRaw = mode;
    return this;
  }
}

class TtyOutput extends PassThrough {
  isTTY = true;
  readonly chunks: Buffer[] = [];

  constructor() {
    super();
    this.on("data", (chunk: Buffer) => this.chunks.push(chunk));
  }

  text(): string {
    return Buffer.concat(this.chunks).toString("utf8");
  }
}

describe("masked secret prompt", () => {
  test("rejects a non-TTY before listening for secret input", async () => {
    const input = new TtyInput();
    input.isTTY = false;
    const output = new TtyOutput();

    await expect(
      readMaskedSecret(
        "Secret key",
        input as unknown as NodeJS.ReadStream,
        output as unknown as NodeJS.WriteStream
      )
    ).rejects.toThrow("Interactive credential entry requires a TTY");

    expect(input.listenerCount("data")).toBe(0);
    expect(input.rawModes).toEqual([]);
  });

  test("masks characters and restores raw mode after submit", async () => {
    const input = new TtyInput();
    input.pause();
    const output = new TtyOutput();

    const result = readMaskedSecret(
      "Secret key",
      input as unknown as NodeJS.ReadStream,
      output as unknown as NodeJS.WriteStream
    );
    input.write("se");
    input.write("cret\r");

    await expect(result).resolves.toBe("secret");
    expect(output.text()).toBe("Secret key        ••••••\n");
    expect(output.text()).not.toContain("secret");
    expect(input.rawModes).toEqual([true, false]);
    expect(input.isPaused()).toBe(true);
  });

  test("pauses an initially idle TTY after submit", async () => {
    const input = new TtyInput();
    const output = new TtyOutput();
    expect(input.readableFlowing).toBeNull();

    const result = readMaskedSecret(
      "Database access",
      input as unknown as NodeJS.ReadStream,
      output as unknown as NodeJS.WriteStream
    );
    input.write("postgresql://example\r");

    await expect(result).resolves.toBe("postgresql://example");
    expect(input.isPaused()).toBe(true);
    expect(input.readableFlowing).toBe(false);
  });

  test("handles backspace without exposing entered characters", async () => {
    const input = new TtyInput();
    const output = new TtyOutput();

    const result = readMaskedSecret(
      "Database access",
      input as unknown as NodeJS.ReadStream,
      output as unknown as NodeJS.WriteStream
    );
    input.write("xy\x7fz\r");

    await expect(result).resolves.toBe("xz");
    expect(output.text()).toBe(
      "Database access   ••\b \b•\n"
    );
    expect(output.text()).not.toMatch(/[xyz]/);
  });

  test("ignores terminal escape sequences generated by modifier-clicks", async () => {
    const input = new TtyInput();
    const output = new TtyOutput();

    const result = readMaskedSecret(
      "Secret key",
      input as unknown as NodeJS.ReadStream,
      output as unknown as NodeJS.WriteStream
    );
    input.write("\x1b[<0;42;");
    input.write("8M");
    input.write("\x1b[12D");
    input.write("secret\r");

    await expect(result).resolves.toBe("secret");
    expect(output.text()).toBe("Secret key        ••••••\n");
  });

  test("restores terminal state when the operator cancels", async () => {
    const input = new TtyInput();
    input.pause();
    const output = new TtyOutput();

    const result = readMaskedSecret(
      "Management token",
      input as unknown as NodeJS.ReadStream,
      output as unknown as NodeJS.WriteStream
    );
    input.write("partial\x03");

    await expect(result).rejects.toBeInstanceOf(
      CredentialSetupCancelledError
    );
    expect(input.rawModes).toEqual([true, false]);
    expect(input.isPaused()).toBe(true);
    expect(output.text()).not.toContain("partial");
  });

  test("restores terminal state when input ends", async () => {
    const input = new TtyInput();
    const output = new TtyOutput();

    const result = readMaskedSecret(
      "Secret key",
      input as unknown as NodeJS.ReadStream,
      output as unknown as NodeJS.WriteStream
    );
    input.end();

    await expect(result).rejects.toBeInstanceOf(
      CredentialSetupCancelledError
    );
    expect(input.rawModes).toEqual([true, false]);
  });
});
